name: 'Action Name'
description: 'What this action does'

inputs:
  who-to-greet:
    description: 'Name to greet'
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time we said hello.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
