name: DeployEnv
on:
 push:
   branches: [main]
   paths-ignore: [.github/**]
 pull_request:
    branches: [ main ]
 schedule:
   - cron: "1,31 8-18 * * 1-5"
 workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy to'
       type: environment
       required: true

jobs:
  FirstJob:
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - run: |
         echo "🎉 The job was triggered by event: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
         echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ." >> $GITHUB_STEP_SUMMARY
         echo "🔎 The name of your branch is ${{ vars.URL }} and your repository is ." >> $GITHUB_STEP_SUMMARY
      - uses: actions/checkout@v7.0.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
